dist: bionic
language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

git:
  depth: 1

before_install:
  - go get -t -v ./...
  - go mod vendor

notifications:
  email: false

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
